name: 'OpenTofu CI/CD Pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  opentofu:
    runs-on: ubuntu-latest
    env:
        ARM_USE_OIDC: true 
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_WORKDIR: terraform

    defaults:
       run:
            shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install OpenTofu
      run: |
          sudo apt update
          sudo apt install curl unzip -y
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method standalone
          tofu version
      working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}
      
              
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID}}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: OpenTofu Init
      run: tofu init
      working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}

    - name: OpenTofu Plan
      run: tofu plan
      working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}

    - name: OpenTofu Apply
      run: tofu apply -auto-approve
      working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}
