name: 'OpenTofu CI/CD Pipeline'

on:
  push:
    branches:
      - main

jobs:
  opentofu:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    defaults:
       run:
            shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3



    - name: Install OpenTofu
      run: |
        wget https://github.com/opentofu/opentofu/releases/download/v1.9.1/opentofu_1.9.1_linux_amd64.zip
        unzip opentofu_1.9.1_linux_amd64.zip
        sudo mv opentofu /usr/local/bin/
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform
      
              
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: OpenTofu Init
      run: tofu init
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform

    - name: OpenTofu Plan
      run: tofu plan
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform

    - name: OpenTofu Apply
      run: tofu apply -auto-approve
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform
