name: 'OpenTofu CI/CD Pipeline'

on:
  push:
    branches:
      - main

jobs:
  opentofu:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    defaults:
       run:
            shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OpenTofu
      uses: hashicorp/setup-terraform@v3
    - name: Install OpenTofu
      run: |
        curl -L -o opentofu.zip https://opentofu.org/downloads/opentofu.zip
        unzip opentofu.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/opentofu


    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    

    - name: OpenTofu Init
      run: OpenTofu init
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform

    - name: OpenTofu Plan
      run: OpenTofu plan
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform

    - name: OpenTofu Apply
      run: OpenTofu apply -auto-approve
      working-directory: /home/runner/work/Opentofu/Opentofu/terraform
