name: 'OpenTofu CI/CD Pipeline'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      plan-result: ${{ steps.plan.outputs.result }}
    env:
        ARM_USE_OIDC: true 
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_WORKDIR: terraform
    defaults:
       run:
            shell: bash
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenTofu
        run: |
          sudo apt update
          sudo apt install curl unzip -y
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method standalone
          tofu version
        working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Tofu Init
        run: tofu init
        working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}

      - name: Tofu Plan
        id: plan
        run: |
          tofu plan
          echo "result=success" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: apply-approval  # ✅ Approval gate here
    if: ${{ github.event_name == 'workflow_dispatch' }}  # Optional: only allow manual apply
    env:
      TF_WORKDIR: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenTofu
        run: |
          sudo apt update
          sudo apt install curl unzip -y
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method standalone
          tofu version
        working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Tofu Apply
        run: tofu apply -auto-approve
        working-directory: ${{ github.workspace }}/${{ env.TF_WORKDIR }}